version: '3'

services:

  initializer:
    build: private-services/background-tasks/initializer
    container_name: "initializer"
    environment:
     - MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    depends_on:
     - mongodb


  public-endpoints:
    build: public-services/endpoints
    container_name: "public-endpoints"
    environment:
     - MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    ports:
     - 8081:3000
    depends_on:
     - mongodb
     - initializer

  admin:
    build: private-services/Admin
    container_name: "admin"
    environment:
     - Settings:MongoDbUri=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    ports:
     - 8082:80
    depends_on:
     - mongodb
     - initializer


  mongodb:
    image: mongo:latest
    container_name: "registration_db"
    environment:
     - MONGO_USER="user"
     - MONGO_PASS="pass"
    ports:
     - 27017:27017
    #command: mongodb --smallfiles --logpath=/dev/null # --quiet


  nginx:
    image: nginx:latest
    ports:
     - "8080:8080"
    volumes:
     - ./nginx/public:/srv/www/static
     - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - mongodb
     - initializer
     #- worker
     #- admin
     - public-endpoints
     #- private-endpoints
     #- public-webite
  