version: '3'

services:

  initializer:
    build: private-services/background-tasks/initializer
    container_name: "initializer"
    networks:
     - privatenet
    env_file: .env
    #environment: (Moved to .env file)
     #- MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    depends_on:
     - mongodb


  public-endpoints:
    build: public-services/endpoints
    container_name: "public-endpoints"
    env_file: .env
    #environment: (Moved to .env file)
     #- MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    ports:
     - 8081:3000
    networks:
     - publicnet
    depends_on:
     - mongodb
     - initializer

  public-website:
    build: public-services/website
    container_name: "public-website"
    env_file: .env
    #environment: (Moved to .env file)
     #- MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    ports:
     - 8082:3000
    networks:
     - publicnet
    depends_on:
     - mongodb
     - initializer
     - public-endpoints

  admin:
    build: private-services/Admin
    container_name: "admin"
    env_file: .env
    #environment: (Moved to .env file)
      #- Settings:ApplicationName=From Compose
      #- Settings:MongoDbUri=mongodb://mongodb:27017 #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    ports:
     - 8083:80
    networks:
     - privatenet
    depends_on:
     - mongodb
     - initializer


  worker:
    build: private-services/background-tasks/Worker
    container_name: "worker"
    env_file: .env
    depends_on:
     - mongodb
     - initializer
    networks:
     - privatenet

  mongodb:
    image: mongo:latest
    container_name: "registration_db"
    env_file: .env
    #environment: (Moved to .env file)
     #- MONGO_USER="user"
     #- MONGO_PASS="pass"
    ports:
     - 27017:27017
    networks:
     - publicnet
     - privatenet
    #command: mongodb --smallfiles --logpath=/dev/null # --quiet


  nginx:
    image: nginx:latest
    ports:
     - "8080:8080"
    networks:
     - publicnet
    volumes:
     - ./nginx/public:/srv/www/static
     - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - mongodb
     - initializer
     - worker
     - admin
     - public-endpoints
     - public-website

networks:
 publicnet:
  #driver: driver-1
 privatenet:
 # driver: driver-2
  