version: '3'

services:

  initializer:
    build: private-services/background-tasks/initializer
    container_name: "initializer"
    environment:
     - MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    depends_on:
     - mongodb

  public-endpoints:
    build: public-services/endpoints
    container_name: "public-endpoints"
    environment:
     - MONGO_DB_URI=mongodb://mongodb:27017/registrations; #<-- replace 'localhost' with 'mongodb' - ie: The name of the docker-compose service
    ports:
     - 8080:3000
    depends_on:
     - mongodb
     - initializer

  mongodb:
    image: mongo:latest
    container_name: "registration_db"
    environment:
     - MONGO_USER="user"
     - MONGO_PASS="pass"
    ports:
     - 27017:27017
    #command: mongodb --smallfiles --logpath=/dev/null # --quiet
  